### ISSUE TITLE
Dependabot::RepoNotFound

### ISSUE THREAD

**Issue by wavemotionio** [dependabot/dependabot-script#362]
Hi All,

We are attempting to run dependabot against an Azure DevOps GIT repository to no avail.  Any assistance would be greatly appreciated. 

Assuming the proper information is:
https://dev.azure.com/ourOrganization/ProjectName/_git/package-name

**Steps are as follows:**

1. clone repo
2. `docker pull dependabot/dependabot-core`
3. `docker run -v "c:/projects/2019/depbot/dependabot-script:/home/dependabot/dependabot-script" -w /home/dependabot/dependabot-script dependabot/dependabot-core bundle install -j 3 --path vendor`
4. `docker run -v "c:/projects/2019/depbot/dependabot-script:/home/dependabot/dependabot-script" -w /home/dependabot/dependabot-script -e PACKAGE_MANAGER=npm_and_yarn -e PROJECT_PATH=ProjectName/_git/package-name -e AZURE_ACCESS_TOKEN=ADO_PAT -e AZURE_HOSTNAME=dev.azure.com/ourOrganization dependabot/dependabot-core bundle exec ruby ./generic-update-script.rb`

**Comment by wavemotionio** [comment]
FYI, many variations on Step 4 have been tested but they ultimately result in the following error:

```
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.4-compliant syntax, but you are running 2.6.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/file_fetchers/base.rb:393:in `rescue in default_branch_for_repo': Dependabot::RepoNotFound (Dependabot::RepoNotFound)
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/file_fetchers/base.rb:389:in `default_branch_for_repo'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/file_fetchers/base.rb:59:in `commit'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/file_fetchers/base.rb:306:in `_full_specification_for'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/file_fetchers/base.rb:316:in `_fetch_file_content'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/file_fetchers/base.rb:88:in `fetch_file_from_host'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.113.1/lib/dependabot/npm_and_yarn/file_fetcher.rb:56:in `package_json'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.113.1/lib/dependabot/npm_and_yarn/file_fetcher.rb:39:in `fetch_files'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/file_fetchers/base.rb:55:in `files'
        from ./generic-update-script.rb:115:in `<main>'
/home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/clients/azure.rb:188:in `get': Dependabot::Clients::Azure::NotFound (Dependabot::Clients::Azure::NotFound)
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/clients/azure.rb:43:in `fetch_default_branch'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/file_fetchers/base.rb:391:in `default_branch_for_repo'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/file_fetchers/base.rb:59:in `commit'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/file_fetchers/base.rb:306:in `_full_specification_for'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/file_fetchers/base.rb:316:in `_fetch_file_content'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/file_fetchers/base.rb:88:in `fetch_file_from_host'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.113.1/lib/dependabot/npm_and_yarn/file_fetcher.rb:56:in `package_json'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.113.1/lib/dependabot/npm_and_yarn/file_fetcher.rb:39:in `fetch_files'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/file_fetchers/base.rb:55:in `files'
        from ./generic-update-script.rb:115:in `<main>'
Fetching npm_and_yarn dependency files for ProjectName/_git/package-name
```

**Comment by LeoColomb** [comment]
> `-e PROJECT_PATH=ProjectName/_git/package-name -e AZURE_ACCESS_TOKEN=ADO_PAT -e AZURE_HOSTNAME=dev.azure.com/ourOrganization`

I think there is something wrong here,, did you test with `-e PROJECT_PATH=ourOrganization/ProjectName/_git/package-name -e AZURE_ACCESS_TOKEN=ADO_PAT -e AZURE_HOSTNAME=dev.azure.com`

**Comment by wavemotionio** [comment]
Hi Leo, thank you for feedback.  Yes, I tried exactly as you have suggested and received the same error, "no repo found". Plus, in that setup we are not specifying a repo so how is the bot supposed to know which repo to look at?

**Comment by wavemotionio** [comment]
Could the ruby version have something to do with it?

`docker run -v "c:/projects/2019/depbot/dependabot-script:/home/dependabot/dependabot-script" -w /home/dependabot/dependabot-script -e PACKAGE_MANAGER=npm_and_yarn -e PROJECT_PATH=ourOrganization/ourProject -e AZURE_ACCESS_TOKEN=ADO_PAT -e AZURE_HOSTNAME=dev.azure.com dependabot/dependabot-core bundle exec ruby ./generic-update-script.rb`

results in:

```
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.4-compliant syntax, but you are running 2.6.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/file_fetchers/base.rb:393:in `rescue in default_branch_for_repo': Dependabot::RepoNotFound (Dependabot::RepoNotFound)
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/file_fetchers/base.rb:389:in `default_branch_for_repo'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/file_fetchers/base.rb:59:in `commit'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/file_fetchers/base.rb:306:in `_full_specification_for'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/file_fetchers/base.rb:316:in `_fetch_file_content'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/file_fetchers/base.rb:88:in `fetch_file_from_host'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.113.1/lib/dependabot/npm_and_yarn/file_fetcher.rb:56:in `package_json'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.113.1/lib/dependabot/npm_and_yarn/file_fetcher.rb:39:in `fetch_files'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/file_fetchers/base.rb:55:in `files'
        from ./generic-update-script.rb:115:in `<main>'
/home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/clients/azure.rb:188:in `get': Dependabot::Clients::Azure::NotFound (Dependabot::Clients::Azure::NotFound)
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/clients/azure.rb:43:in `fetch_default_branch'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/file_fetchers/base.rb:391:in `default_branch_for_repo'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/file_fetchers/base.rb:59:in `commit'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/file_fetchers/base.rb:306:in `_full_specification_for'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/file_fetchers/base.rb:316:in `_fetch_file_content'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/file_fetchers/base.rb:88:in `fetch_file_from_host'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.113.1/lib/dependabot/npm_and_yarn/file_fetcher.rb:56:in `package_json'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.113.1/lib/dependabot/npm_and_yarn/file_fetcher.rb:39:in `fetch_files'
        from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.1/lib/dependabot/file_fetchers/base.rb:55:in `files'
        from ./generic-update-script.rb:115:in `<main>'
Fetching npm_and_yarn dependency files for ourOrganization/ourProject
```

**Comment by LeoColomb** [comment]
> Could the ruby version have something to do with it?

No.
I think there is a problem with the defined endpoint.

https://github.com/dependabot/dependabot-script/blob/a0bf84c24fec48717040d6c04dc7a7c266e5eb06/generic-update-script.rb#L92

https://docs.microsoft.com/en-us/rest/api/azure/devops/git/commits/get?view=azure-devops-rest-5.1

**Comment by wavemotionio** [comment]
Got it, so first we need a fix in dependabot-core? https://github.com/dependabot/dependabot-core/blob/master/common/lib/dependabot/clients/azure.rb

**Comment by LeoColomb** [comment]
Nope, right in this script, at the line I mentioned! @dependabot' team should be able to help you on this.

**Comment by wavemotionio** [comment]
Alright, I think we made some progress. Two changes:

1. updated the line you mentioned to `https://#{azure_hostname}`
2. `docker run -v "c:/projects/2019/depbot/dependabot-script:/home/dependabot/dependabot-script" -w /home/dependabot/dependabot-script -e PACKAGE_MANAGER=npm_and_yarn -e PROJECT_PATH=organization/project/package -e AZURE_ACCESS_TOKEN=token -e AZURE_HOSTNAME=dev.azure.com dependabot/dependabot-core bundle exec ruby ./generic-update-script.rb`

New errors indicate `getaddrinfo': getaddrinfo: Name or service not known (SocketError) (Excon::Error::Socket)` which is seems to share systems with an old issue regarding our private npm feed: https://github.com/dependabot/dependabot-core/issues/943

**Comment by LeoColomb** [comment]
> * updated the line you mentioned to `https://#{azure_hostname}`

`https://#{azure_hostname}/`? Note the `/` ending.

**Comment by wavemotionio** [comment]
Arg, back to Dependabot::RepoNotFound.

**Comment by LeoColomb** [comment]
`https://#{azure_hostname}/` **and** `PROJECT_PATH=ourOrganization/ProjectName/_git/package-name`?

**Comment by wavemotionio** [comment]
Yes! I believe that worked, thank you!

**Comment by LeoColomb** [comment]
Well, can you let this issue opened? There is something to fix in the repo.

**Comment by wavemotionio** [comment]
Oh sure!
