### ISSUE TITLE
"pyenv: version `3.8.5' is not installed" for poetry (pip)

### ISSUE THREAD

**Issue by apollo13** [dependabot/dependabot-script#477]
This seems to be the same as #387 with a newer python version:

```
Parsing dependencies information
/builds/ops/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-python-0.118.8/lib/dependabot/python/update_checker/poetry_version_resolver.rb:317:in `run_poetry_command': pyenv: version `3.8.5' is not installed (set by /builds/ops/dependabot-script/tmp/dependabot_20201005-12-75dkyl/.python-version) (Dependabot::SharedHelpers::HelperSubprocessFailed)
	from /builds/ops/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-python-0.118.8/lib/dependabot/python/update_checker/poetry_version_resolver.rb:84:in `block (2 levels) in fetch_latest_resolvable_version_string'
	from /builds/ops/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:141:in `with_git_configured'
	from /builds/ops/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-python-0.118.8/lib/dependabot/python/update_checker/poetry_version_resolver.rb:72:in `block in fetch_latest_resolvable_version_string'
	from /builds/ops/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:37:in `block (2 levels) in in_a_temporary_directory'
	from /builds/ops/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:37:in `chdir'
	from /builds/ops/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:37:in `block in in_a_temporary_directory'
	from /usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	from /builds/ops/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:34:in `in_a_temporary_directory'
	from /builds/ops/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-python-0.118.8/lib/dependabot/python/update_checker/poetry_version_resolver.rb:71:in `fetch_latest_resolvable_version_string'
	from /builds/ops/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-python-0.118.8/lib/dependabot/python/update_checker/poetry_version_resolver.rb:42:in `latest_resolvable_version'
	from /builds/ops/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-python-0.118.8/lib/dependabot/python/update_checker.rb:43:in `latest_resolvable_version'
	from /builds/ops/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/update_checkers/base.rb:72:in `preferred_resolvable_version'
	from /builds/ops/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/update_checkers/base.rb:235:in `preferred_version_resolvable_with_unlock?'
	from /builds/ops/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/update_checkers/base.rb:227:in `numeric_version_can_update?'
	from /builds/ops/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/update_checkers/base.rb:177:in `version_can_update?'
	from /builds/ops/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/update_checkers/base.rb:40:in `can_update?'
	from ./generic-update-script.rb:147:in `block in <main>'
	from ./generic-update-script.rb:130:in `each'
	from ./generic-update-script.rb:130:in `<main>'
```

**Comment by m-aciek** [comment]
I believe it's fixed now.

**Comment by m-aciek** [comment]
Fixed by https://github.com/dependabot/dependabot-script/pull/544.
