### ISSUE TITLE
Custom CI Config Path for Gitlab Does Not Work

### ISSUE THREAD

**Issue by mountainraptor** [dependabot/dependabot-script#481]
In the readme there is a link to use a custom configuration path following these instructions: https://docs.gitlab.com/ee/ci/pipelines/settings.html#custom-ci-configuration-path.

When I copy the .gitlab-ci.example.yml to .gitlab-ci.yml everything works. When I set the custom config path to point to .gitlab-ci.example.yml it throws an error in the gitlab-runner:

```
$ bundle exec ruby ./generic-update-script.rb
/builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/file_fetchers/base.rb:395:in `rescue in default_branch_for_repo': Dependabot::RepoNotFound (Dependabot::RepoNotFound)
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/file_fetchers/base.rb:391:in `default_branch_for_repo'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/file_fetchers/base.rb:61:in `commit'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/file_fetchers/base.rb:310:in `_full_specification_for'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/file_fetchers/base.rb:320:in `_fetch_file_content'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/file_fetchers/base.rb:90:in `fetch_file_from_host'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.118.8/lib/dependabot/npm_and_yarn/file_fetcher.rb:54:in `package_json'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.118.8/lib/dependabot/npm_and_yarn/file_fetcher.rb:37:in `fetch_files'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/file_fetchers/base.rb:55:in `files'
	from ./generic-update-script.rb:115:in `'
/builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/octokit-4.18.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/simplesense/frontend: 404 - Not Found // See: https://docs.github.com/rest/reference/repos#get-a-repository (Octokit::NotFound)
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:12:in `block in call'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:65:in `on_complete'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:11:in `call'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/octokit-4.18.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/octokit-4.18.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/request/retry.rb:148:in `call'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/rack_builder.rb:153:in `build_response'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/connection.rb:492:in `run_request'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/connection.rb:198:in `get'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/octokit-4.18.0/lib/octokit/connection.rb:156:in `request'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/octokit-4.18.0/lib/octokit/connection.rb:19:in `get'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/octokit-4.18.0/lib/octokit/client/repositories.rb:29:in `repository'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/clients/github_with_retries.rb:95:in `public_send'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/clients/github_with_retries.rb:95:in `block in method_missing'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/clients/github_with_retries.rb:115:in `retry_connection_failures'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/clients/github_with_retries.rb:92:in `method_missing'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/clients/github_with_retries.rb:66:in `fetch_default_branch'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/file_fetchers/base.rb:393:in `default_branch_for_repo'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/file_fetchers/base.rb:61:in `commit'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/file_fetchers/base.rb:310:in `_full_specification_for'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/file_fetchers/base.rb:320:in `_fetch_file_content'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/file_fetchers/base.rb:90:in `fetch_file_from_host'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.118.8/lib/dependabot/npm_and_yarn/file_fetcher.rb:54:in `package_json'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.118.8/lib/dependabot/npm_and_yarn/file_fetcher.rb:37:in `fetch_files'
	from /builds/simplesense/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/file_fetchers/base.rb:55:in `files'
	from ./generic-update-script.rb:115:in `'
Fetching npm_and_yarn dependency files for simplesense/frontend
Cleaning up file based variables
00:01
ERROR: Job failed: exit code 1
```

**Comment by mountainraptor** [comment]
Error resulted from protected variables not being available on a default branch and failing to access the repository.
