### ISSUE TITLE
Problem with Composer dependencies in GitlabCI

### ISSUE THREAD

**Issue by h-stoyanov** [dependabot/dependabot-script#505]
Hello. My pipelines started to fail because of strange bug. I think this is related to the composer version 2 and how this is handled in the **dependabot-core** project. Here is sanitized output from the pipeline
```
$ bundle exec ruby ./generic-update-script.rb
Fetching composer dependency files for my-user/my-project
Parsing dependencies information
/builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:116:in `rescue in run_helper_subprocess': Could not open input file: /opt/composer/helpers/bin/run (Dependabot::SharedHelpers::HelperSubprocessFailed)
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:84:in `run_helper_subprocess'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-composer-0.118.8/lib/dependabot/composer/update_checker/version_resolver.rb:126:in `block in run_update_checker'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:141:in `with_git_configured'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-composer-0.118.8/lib/dependabot/composer/update_checker/version_resolver.rb:125:in `run_update_checker'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-composer-0.118.8/lib/dependabot/composer/update_checker/version_resolver.rb:76:in `block in fetch_latest_resolvable_version_string'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:37:in `block (2 levels) in in_a_temporary_directory'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:37:in `chdir'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:37:in `block in in_a_temporary_directory'
	from /usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:34:in `in_a_temporary_directory'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-composer-0.118.8/lib/dependabot/composer/update_checker/version_resolver.rb:74:in `fetch_latest_resolvable_version_string'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-composer-0.118.8/lib/dependabot/composer/update_checker/version_resolver.rb:59:in `fetch_latest_resolvable_version'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-composer-0.118.8/lib/dependabot/composer/update_checker/version_resolver.rb:49:in `latest_resolvable_version'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-composer-0.118.8/lib/dependabot/composer/update_checker.rb:34:in `latest_resolvable_version'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/update_checkers/base.rb:72:in `preferred_resolvable_version'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/update_checkers/base.rb:235:in `preferred_version_resolvable_with_unlock?'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/update_checkers/base.rb:227:in `numeric_version_can_update?'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/update_checkers/base.rb:177:in `version_can_update?'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/update_checkers/base.rb:40:in `can_update?'
	from ./generic-update-script.rb:147:in `block in <main>'
	from ./generic-update-script.rb:130:in `each'
	from ./generic-update-script.rb:130:in `<main>'
/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse': 767: unexpected token at 'Could not open input file: /opt/composer/helpers/bin/run (JSON::ParserError)
'
	from /usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:108:in `run_helper_subprocess'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-composer-0.118.8/lib/dependabot/composer/update_checker/version_resolver.rb:126:in `block in run_update_checker'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:141:in `with_git_configured'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-composer-0.118.8/lib/dependabot/composer/update_checker/version_resolver.rb:125:in `run_update_checker'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-composer-0.118.8/lib/dependabot/composer/update_checker/version_resolver.rb:76:in `block in fetch_latest_resolvable_version_string'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:37:in `block (2 levels) in in_a_temporary_directory'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:37:in `chdir'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:37:in `block in in_a_temporary_directory'
	from /usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:34:in `in_a_temporary_directory'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-composer-0.118.8/lib/dependabot/composer/update_checker/version_resolver.rb:74:in `fetch_latest_resolvable_version_string'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-composer-0.118.8/lib/dependabot/composer/update_checker/version_resolver.rb:59:in `fetch_latest_resolvable_version'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-composer-0.118.8/lib/dependabot/composer/update_checker/version_resolver.rb:49:in `latest_resolvable_version'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-composer-0.118.8/lib/dependabot/composer/update_checker.rb:34:in `latest_resolvable_version'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/update_checkers/base.rb:72:in `preferred_resolvable_version'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/update_checkers/base.rb:235:in `preferred_version_resolvable_with_unlock?'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/update_checkers/base.rb:227:in `numeric_version_can_update?'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/update_checkers/base.rb:177:in `version_can_update?'
	from /builds/my-user/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/update_checkers/base.rb:40:in `can_update?'
	from ./generic-update-script.rb:147:in `block in <main>'
	from ./generic-update-script.rb:130:in `each'
	from ./generic-update-script.rb:130:in `<main>'
Cleaning up file based variables
00:03
ERROR: Job failed: exit code 1
```

**Comment by brambaud** [comment]
Hello :)

I had the same issue this week.

Everything went fine after updating **dependabot-omnibus** gem to version 0.129.0 [which contains composer v2 support](https://github.com/dependabot/dependabot-core/issues/2668)

**Comment by h-stoyanov** [comment]
> Hello :)
> 
> I had the same issue this week.
> 
> Everything went fine after updating **dependabot-omnibus** gem to version 0.129.0 [which contains composer v2 support](https://github.com/dependabot/dependabot-core/issues/2668)

I did this already but now I'm facing new problems with the network connection via docker

**Comment by h-stoyanov** [comment]
Bumping up the version of the **dependabot-omnibus** gem to version 0.129.0 solved the problem but then I faced new problem with network timeout. I've managed to overcome it by raising the maximum retries.
