### ISSUE TITLE
Dependabot::RepoNotFound

### ISSUE THREAD

**Issue by kwlin** [dependabot/dependabot-script#507]
Hi everybody, 

I'm currently trying to run dependabot within Azure DevOps. I have setup a build pipeline with yaml (with a valid project path of course ;) ) to check a git repo on Azure DevOps:

```YAML
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '=2.6'

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: |
    bundle exec ruby ./generic-update-script.rb
  env:
    AZURE_HOSTNAME: dev.azure.com
    AZURE_ACCESS_TOKEN: $(PersonalAccessToken)
    PROJECT_PATH: <organisation name>/<project name>/_git/<repo name>
    PACKAGE_MANAGER: nuget
  displayName: 'Update dependencies'
```

But I keep getting the following error when running the script generic-upate-script-rb:

```
/opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.118.16/lib/dependabot/file_fetchers/base.rb:399:in `rescue in default_branch_for_repo': Dependabot::RepoNotFound (Dependabot::RepoNotFound)
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.118.16/lib/dependabot/file_fetchers/base.rb:395:in `default_branch_for_repo'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.118.16/lib/dependabot/file_fetchers/base.rb:61:in `commit'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.118.16/lib/dependabot/file_fetchers/base.rb:314:in `_full_specification_for'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.118.16/lib/dependabot/file_fetchers/base.rb:129:in `_fetch_repo_contents'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.118.16/lib/dependabot/file_fetchers/base.rb:114:in `repo_contents'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-nuget-0.118.16/lib/dependabot/nuget/file_fetcher.rb:184:in `csproj_file'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-nuget-0.118.16/lib/dependabot/nuget/file_fetcher.rb:57:in `project_files'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-nuget-0.118.16/lib/dependabot/nuget/file_fetcher.rb:28:in `fetch_files'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.118.16/lib/dependabot/file_fetchers/base.rb:55:in `files'
	from ./generic-update-script.rb:115:in `<main>'
/opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.118.16/lib/dependabot/clients/azure.rb:188:in `get': Dependabot::Clients::Azure::NotFound (Dependabot::Clients::Azure::NotFound)
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.118.16/lib/dependabot/clients/azure.rb:43:in `fetch_default_branch'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.118.16/lib/dependabot/file_fetchers/base.rb:397:in `default_branch_for_repo'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.118.16/lib/dependabot/file_fetchers/base.rb:61:in `commit'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.118.16/lib/dependabot/file_fetchers/base.rb:314:in `_full_specification_for'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.118.16/lib/dependabot/file_fetchers/base.rb:129:in `_fetch_repo_contents'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.118.16/lib/dependabot/file_fetchers/base.rb:114:in `repo_contents'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-nuget-0.118.16/lib/dependabot/nuget/file_fetcher.rb:184:in `csproj_file'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-nuget-0.118.16/lib/dependabot/nuget/file_fetcher.rb:57:in `project_files'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-nuget-0.118.16/lib/dependabot/nuget/file_fetcher.rb:28:in `fetch_files'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.118.16/lib/dependabot/file_fetchers/base.rb:55:in `files'
	from ./generic-update-script.rb:115:in `<main>'
```
It's the same issue as described in #362 but I'm using the recent version of the dependabot-script with hostname dev.azure.com. 

I've verified the following things:
* The PersonalAccessToken has enough rights to call the API of Azure DevOps. (Read & write acces to the GIT repo)
* The url seems correct. I can browse to the url https://<azure_hostname>/<project_path> and access the git repo.
* Generic-update-script.rb is using https://dev.azure.com/ instead of https://#{azure_hostname}/api/v4 so the fix is applied.
* I've tried the reproduction steps described in #362 and could reproduce the issue. But I couldn't get extra information out of it.
* I'm using ruby version 2.6.6 & dependabot 0.118.16 (also tried version 0.129.0 of dependabot but no luck)

Does anybody have any pointers for me so I can debug or (even better) fix my issue?

**Comment by jeffwidman** [comment]
We've updated this repo's README with a [deprecation note](https://github.com/dependabot/dependabot-script?tab=readme-ov-file#this-repo-is-deprecated) which points to a [new example repo](https://github.com/dependabot/example-cli-usage/) we setup to demonstrate how to self-host Dependabot using the [Dependabot CLI](https://github.com/dependabot/cli). As a result, we are archiving this repo.
