### ISSUE TITLE
Gitlab auto-merge returns 405

### ISSUE THREAD

**Issue by jingsam** [dependabot/dependabot-script#528]
I set up a dependabot in my private gitlab group, enable auto-merge feature, returns 405 Method Not Allowed error:

```
- Updating eslint-plugin-prettier (from 3.3.0)…/builds/geoway/dependabot-script/vendor/ruby/2.6.0/gems/gitlab-4.16.1/lib/gitlab/request.rb:61:in `validate': Server responded with code 405, message: 405 Method Not Allowed. Request URI: https://gitlab.com/api/v4/projects/geoway%2Fatlas-vision/merge_requests/113/merge (Gitlab::Error::MethodNotAllowed)
	from /builds/geoway/dependabot-script/vendor/ruby/2.6.0/gems/gitlab-4.16.1/lib/gitlab/request.rb:53:in `block (2 levels) in <class:Request>'
	from /builds/geoway/dependabot-script/vendor/ruby/2.6.0/gems/gitlab-4.16.1/lib/gitlab/client/merge_requests.rb:136:in `accept_merge_request'
	from ./generic-update-script.rb:194:in `block in <main>'
	from ./generic-update-script.rb:130:in `each'
	from ./generic-update-script.rb:130:in `<main>'
```

**Comment by Nothing4You** [comment]
related to #538

**Comment by jeffwidman** [comment]
We've updated this repo's README with a [deprecation note](https://github.com/dependabot/dependabot-script?tab=readme-ov-file#this-repo-is-deprecated) which points to a [new example repo](https://github.com/dependabot/example-cli-usage/) we setup to demonstrate how to self-host Dependabot using the [Dependabot CLI](https://github.com/dependabot/cli). As a result, we are archiving this repo.

While the new example repo runs on GitHub Actions, nothing in the Dependabot bits are specific to GitHub, so it should be straightforward to port it to any other CI system.
