### ISSUE TITLE
Terraform fails parsing

### ISSUE THREAD

**Issue by joonvena** [dependabot/dependabot-script#665]
I'm trying to execute dependabot-script for Terraform repository. Currently for testing i only made repository with versions.tf file that contains the providers with versions. If i run this i only get output:

`
Fetching terraform dependency files for xxx
Parsing dependencies information
Done
`

But don't see any MR's raised in the repository. If i add another file output.tf it fails to parse that:

`
Parsing dependencies information
/home/dependabot/.bundle/gems/dependabot-terraform-0.142.0/lib/dependabot/terraform/file_parser.rb:239:in `rescue in parsed_file': unable to parse HCL: At 2:11: Unknown token: 2:11 IDENT google_cloudfunctions_function.function.https_trigger_url (Dependabot::DependencyFileNotParseable)
	from /home/dependabot/.bundle/gems/dependabot-terraform-0.142.0/lib/dependabot/terraform/file_parser.rb:213:in `parsed_file'
	from /home/dependabot/.bundle/gems/dependabot-terraform-0.142.0/lib/dependabot/terraform/file_parser.rb:25:in `block in parse'
	from /home/dependabot/.bundle/gems/dependabot-terraform-0.142.0/lib/dependabot/terraform/file_parser.rb:24:in `each'
	from /home/dependabot/.bundle/gems/dependabot-terraform-0.142.0/lib/dependabot/terraform/file_parser.rb:24:in `parse'
	from ./generic-update-script.rb:167:in `<main>'
/home/dependabot/.bundle/gems/dependabot-terraform-0.142.0/lib/dependabot/terraform/file_parser.rb:225:in `block in parsed_file': unable to parse HCL: At 2:11: Unknown token: 2:11 IDENT google_cloudfunctions_function.function.https_trigger_url (Dependabot::SharedHelpers::HelperSubprocessFailed)
	from /home/dependabot/.bundle/gems/dependabot-common-0.142.0/lib/dependabot/shared_helpers.rb:45:in `block (2 levels) in in_a_temporary_directory'
	from /home/dependabot/.bundle/gems/dependabot-common-0.142.0/lib/dependabot/shared_helpers.rb:45:in `chdir'
	from /home/dependabot/.bundle/gems/dependabot-common-0.142.0/lib/dependabot/shared_helpers.rb:45:in `block in in_a_temporary_directory'
	from /usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	from /home/dependabot/.bundle/gems/dependabot-common-0.142.0/lib/dependabot/shared_helpers.rb:42:in `in_a_temporary_directory'
	from /home/dependabot/.bundle/gems/dependabot-terraform-0.142.0/lib/dependabot/terraform/file_parser.rb:216:in `parsed_file'
	from /home/dependabot/.bundle/gems/dependabot-terraform-0.142.0/lib/dependabot/terraform/file_parser.rb:25:in `block in parse'
	from /home/dependabot/.bundle/gems/dependabot-terraform-0.142.0/lib/dependabot/terraform/file_parser.rb:24:in `each'
	from /home/dependabot/.bundle/gems/dependabot-terraform-0.142.0/lib/dependabot/terraform/file_parser.rb:24:in `parse'
	from ./generic-update-script.rb:167:in `<main>'
`

**Comment by jeffwidman** [comment]
We've updated this repo's README with a [deprecation note](https://github.com/dependabot/dependabot-script?tab=readme-ov-file#this-repo-is-deprecated) which points to a [new example repo](https://github.com/dependabot/example-cli-usage/) we setup to demonstrate how to self-host Dependabot using the [Dependabot CLI](https://github.com/dependabot/cli). As a result, we are archiving this repo.
