### ISSUE TITLE
Azure DevOps: undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by mikeKuester** [dependabot/dependabot-script#792]
Hello,

I tried to run dependabot within Azure DevOps, first by using the [Dependabot marketplace extension](https://marketplace.visualstudio.com/items?itemName=tingle-software.dependabot) but after geting always an "error 1" from the process '/usr/bin/docker', I'm now using the dependabot-script. I run also into an error, but with a clearer error:

>  'organization': undefined method 'split' for nil:NilClass (NoMethodError)

This is my yaml for the pipeline:

```yaml
trigger: none # Disable CI trigger

schedules:
- cron: '0 2 * * *' # daily at 2am UTC
  always: true # run even when there are no code changes
  branches:
    include:
      - master
  # batch: true
  displayName: Daily

pool:
  vmImage: 'ubuntu-latest' # requires macos or ubuntu (windows is not supported)

variables:
  - name: DIRECTORY_PATH
    value: /
  - name: PACKAGE_MANAGER
    value: nuget
  - name: PROJECT_PATH
    value: myOrg/_git/projectName
  - name: AZURE_HOSTNAME
    value: dev.azure.com
    
steps:
  - script: git clone https://github.com/dependabot/dependabot-script.git
    displayName: Clone Dependabot config repo
    
  - script: |
      cd dependabot-script
      docker build -t "dependabot/dependabot-script" -f Dockerfile .
    displayName:  Build Dependabot Image
     
  - script: |
      docker run --rm -e AZURE_ACCESS_TOKEN='$(PAT)' dependabot/dependabot-script
    displayName: Run Dependabot
```

For testing I created a token with "full access" and store it in the variable PAT as a secret.

But the job fails always during the execution of dependabot:

```
Starting: Run Dependabot
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.201.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
docker run --rm -e AZURE_ACCESS_TOKEN='$(PAT)' dependabot/dependabot-script
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/0592e700-eede-4b9b-bba8-d26541bb36a9.sh
/home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.172.2/lib/dependabot/source.rb:152:in `organization': undefined method `split' for nil:NilClass (NoMethodError)
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.172.2/lib/dependabot/clients/azure.rb:64:in `fetch_default_branch'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.172.2/lib/dependabot/file_fetchers/base.rb:469:in `default_branch_for_repo'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.172.2/lib/dependabot/file_fetchers/base.rb:71:in `commit'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.172.2/lib/dependabot/file_fetchers/base.rb:386:in `_full_specification_for'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.172.2/lib/dependabot/file_fetchers/base.rb:176:in `_fetch_repo_contents'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.172.2/lib/dependabot/file_fetchers/base.rb:163:in `repo_contents'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.172.2/lib/dependabot/file_fetchers/base.rb:103:in `fetch_file_if_present'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-bundler-0.172.2/lib/dependabot/bundler/file_fetcher.rb:64:in `gemfile'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-bundler-0.172.2/lib/dependabot/bundler/file_fetcher.rb:30:in `fetch_files'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.172.2/lib/dependabot/file_fetchers/base.rb:65:in `files'
	from ./generic-update-script.rb:154:in `<main>'
Fetching bundler dependency files for 
##[error]Bash exited with code '1'.
Finishing: Run Dependabot
```

I started with a project with severals repos and the "full path" and also tried it here with a simpler project with just one repo.

**Comment by brrygrdn** [comment]
Hi @mikeKuester, I think the issue might be that the final `docker run` command will need all of the envvars passed through using the `-e` argument.

From looking at the bug, we attempt to determine the org name via a split [here](https://github.com/dependabot/dependabot-core/blob/58e63a5d538a423482b028ccee26e7514505effa/common/lib/dependabot/source.rb#L151-L153) in dependabot-core, we get the exception you are seeing:

```ruby
    def organization
      repo.split("/").first
    end
```

The value of `repo` is directly set in the ./generic-update-script.rb` here:
https://github.com/dependabot/dependabot-script/blob/56c43fa18ebb1db200ea1076404a261eab843317/generic-update-script.rb#L92-L99

We obtain the repo name from the ENVVARs here:
https://github.com/dependabot/dependabot-script/blob/56c43fa18ebb1db200ea1076404a261eab843317/generic-update-script.rb#L22

I think it should work ok if you update the script to something like:
```
docker run --rm -e AZURE_ACCESS_TOKEN='$(PAT)' -e PROJECT_PATH='$(PROJECT_PATH)' -e  PACKAGE_MANAGER='$(PACKAGE_MANAGER)' dependabot/dependabot-script
```

The values you are using for `DIRECTORY_PATH` and `AZURE_HOSTNAME` are the defaults so I've omitted them, but they should be passed as well if you need to change them.

**Comment by mikeKuester** [comment]
@brrygrdn Thanks for your answer. I got it finally working now, but I add my way to that point. Maybe that can help someone else.



### Steps to get it working ...

If I extend the arguments as mentioned, the "undefined method" error disappears, but the next one occures: Dependabot::**DependencyFileNotFound**


```
Starting: Run Dependabot
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.201.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
docker run --rm -e AZURE_ACCESS_TOKEN='***' -e PROJECT_PATH='bts-ai/_git/DependabotTest' -e  PACKAGE_MANAGER='nuget' dependabot/dependabot-script
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/2b756613-e50b-4b94-b75d-fceb0e8bfd09.sh
/home/dependabot/dependabot-script/.bundle/gems/dependabot-nuget-0.172.2/lib/dependabot/nuget/file_fetcher.rb:42:in `fetch_files': Dependabot::DependencyFileNotFound (Dependabot::DependencyFileNotFound)
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.172.2/lib/dependabot/file_fetchers/base.rb:65:in `files'
	from ./generic-update-script.rb:154:in `<main>'
Fetching nuget dependency files for bts-ai/_git/DependabotTest
##[error]Bash exited with code '1'.
Finishing: Run Dependabot

```

This is the same error as the one mentioned here: https://github.com/acraven/azure-dependabot/issues/7
but an actual .NET solution / project doesn't use nuget.config. 

.csproj file
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommonServiceLocator" Version="2.0.6" />
    <PackageReference Include="SharpZipLib" Version="0.86.0" />
  </ItemGroup>

</Project>
```

.sln file
```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
VisualStudioVersion = 17.2.32616.157
MinimumVisualStudioVersion = 10.0.40219.1
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "DepenabotTestApp", "DepenabotTestApp.csproj", "{F408664A-DB49-4F94-8338-7CA855928EB9}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{F408664A-DB49-4F94-8338-7CA855928EB9}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{F408664A-DB49-4F94-8338-7CA855928EB9}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{F408664A-DB49-4F94-8338-7CA855928EB9}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{F408664A-DB49-4F94-8338-7CA855928EB9}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {4129DDDA-907E-4406-9B0A-490FDAD210BD}
	EndGlobalSection
EndGlobal
```



My PROJECT_PATH points to the repo, but not to the folder with the .NET solution file. If I add that (PROJECT_PATH  = bts-ai/_git/DependabotTest/DepenabotTestApp) a different error occures: Dependabot::RepoNotFound


```
Starting: Run Dependabot
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.201.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
docker run --rm -e AZURE_ACCESS_TOKEN='***' -e PROJECT_PATH='bts-ai/_git/DependabotTest/DepenabotTestApp' -e  PACKAGE_MANAGER='nuget' dependabot/dependabot-script
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/1b16c3ac-d6e3-422e-8229-dcbc962ee7eb.sh
/home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.172.2/lib/dependabot/file_fetchers/base.rb:471:in `rescue in default_branch_for_repo': Dependabot::RepoNotFound (Dependabot::RepoNotFound)
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.172.2/lib/dependabot/file_fetchers/base.rb:467:in `default_branch_for_repo'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.172.2/lib/dependabot/file_fetchers/base.rb:71:in `commit'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.172.2/lib/dependabot/file_fetchers/base.rb:386:in `_full_specification_for'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.172.2/lib/dependabot/file_fetchers/base.rb:176:in `_fetch_repo_contents'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.172.2/lib/dependabot/file_fetchers/base.rb:163:in `repo_contents'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-nuget-0.172.2/lib/dependabot/nuget/file_fetcher.rb:184:in `csproj_file'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-nuget-0.172.2/lib/dependabot/nuget/file_fetcher.rb:55:in `project_files'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-nuget-0.172.2/lib/dependabot/nuget/file_fetcher.rb:28:in `fetch_files'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.172.2/lib/dependabot/file_fetchers/base.rb:65:in `files'
	from ./generic-update-script.rb:154:in `<main>'
/home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.172.2/lib/dependabot/clients/azure.rb:239:in `get': Dependabot::Clients::Azure::NotFound (Dependabot::Clients::Azure::NotFound)
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.172.2/lib/dependabot/clients/azure.rb:63:in `fetch_default_branch'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.172.2/lib/dependabot/file_fetchers/base.rb:469:in `default_branch_for_repo'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.172.2/lib/dependabot/file_fetchers/base.rb:71:in `commit'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.172.2/lib/dependabot/file_fetchers/base.rb:386:in `_full_specification_for'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.172.2/lib/dependabot/file_fetchers/base.rb:176:in `_fetch_repo_contents'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.172.2/lib/dependabot/file_fetchers/base.rb:163:in `repo_contents'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-nuget-0.172.2/lib/dependabot/nuget/file_fetcher.rb:184:in `csproj_file'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-nuget-0.172.2/lib/dependabot/nuget/file_fetcher.rb:55:in `project_files'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-nuget-0.172.2/lib/dependabot/nuget/file_fetcher.rb:28:in `fetch_files'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.172.2/lib/dependabot/file_fetchers/base.rb:65:in `files'
	from ./generic-update-script.rb:154:in `<main>'
Fetching nuget dependency files for bts-ai/_git/DependabotTest/DepenabotTestApp
##[error]Bash exited with code '1'.
Finishing: Run Dependabot
```

The file structure is very simple:
```
DependabotTest
|
- .git
|
- DependabotTestApp 
  |
  - DepenabotTestApp.sln
  - DepenabotTestApp.csproj
  - Program.cs
```

Ok, I have to define the PROJECT_PATH (to the git repo) _and_ the DIRECTORY_PATH (to the .NET solution):

```YAML
variables:
  - name: PACKAGE_MANAGER
    value: nuget
  - name: PROJECT_PATH
    value: bts-ai/_git/DependabotTest  # path to the repo
  - name: DIRECTORY_PATH
    value: /DepenabotTestApp # sub-path to the .sln file
```

And I have to add the variable also to the _docker run_ arguments:
```YAML
  - script: |
      docker run --rm -e AZURE_ACCESS_TOKEN='$(PAT)' -e PROJECT_PATH='$(PROJECT_PATH)' -e DIRECTORY_PATH='$(DIRECTORY_PATH)' -e  PACKAGE_MANAGER='$(PACKAGE_MANAGER)' dependabot/dependabot-script
    displayName: Run Dependabot
```


Now it works and creates a new branch and a pull request for the vulnerable package! 😍

```
Starting: Run Dependabot
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.201.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
docker run --rm -e AZURE_ACCESS_TOKEN='***' -e PROJECT_PATH='bts-ai/_git/DependabotTest' -e DIRECTORY_PATH='/DepenabotTestApp' -e  PACKAGE_MANAGER='nuget' dependabot/dependabot-script
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/33d321d8-9860-4d70-8889-1fc77905298d.sh
Fetching nuget dependency files for bts-ai/_git/DependabotTest
Parsing dependencies information
  - Updating SharpZipLib (from 0.86.0)… submitted
Done
Finishing: Run Dependabot
```
