### ISSUE TITLE
Failing to connect to api.github.com, despite only specifying GitHub Enterprise

### ISSUE THREAD

**Issue by troypoulter** [dependabot/dependabot-script#856]
I've been following the guide https://github.com/dependabot/dependabot-script#running-script-with-dependabot-script-dockerfile to run this on my work laptop against our on-prem GitHub Enterprise server for an npm project.

Here is the Docker command I'm running after I built the image locally:

`docker run --rm --env "DEPENDABOT_OPEN_TIMEOUT_IN_SECONDS=30" --env "PROJECT_PATH=<org>/<repo>" --env "PACKAGE_MANAGER=npm_and_yarn" --env "GITHUB_ENTERPRISE_ACCESS_TOKEN=<token>" --env "GITHUB_ENTERPRISE_HOSTNAME=<hostname: in format like 'github.com'>" "dependabot/dependabot-script"`

Please check the bottom for the full log as it's quite long.

I'm running it on `dependabot/dependabot-core:0.209.0` and just cloned this repo today, so everything should be the latest.

I am unsure why it is even connecting to `api.github.com` as I am only passing through my GHES hostname.

I stumbled across https://github.com/dependabot/dependabot-core/pull/4964 and have provided that env var now to give it more time, even when I increase it much higher the same result as inside the work proxy we aren't able to connect to `api.github.com`. 

Please let me know if I can provide any extra info!

## Error log

```log
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
Running with options: {}
Fetching npm_and_yarn dependency files for <org>/<repo>
Parsing dependencies information
  - Updating @emotion/react (from 11.10.0)…/usr/local/lib/ruby/2.7.0/net/http.rb:960:in `initialize': Failed to open TCP connection to api.github.com:443 (getaddrinfo: Temporary failure in name resolution) (Faraday::ConnectionFailed)
        from /usr/local/lib/ruby/2.7.0/net/http.rb:960:in `open'
        from /usr/local/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
        from /usr/local/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
        from /usr/local/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
        from /usr/local/lib/ruby/2.7.0/net/http.rb:958:in `connect'
        from /usr/local/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
        from /usr/local/lib/ruby/2.7.0/net/http.rb:932:in `start'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-net_http-2.1.0/lib/faraday/adapter/net_http.rb:137:in `request_via_get_method'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-net_http-2.1.0/lib/faraday/adapter/net_http.rb:128:in `request_with_wrapped_block'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-net_http-2.1.0/lib/faraday/adapter/net_http.rb:121:in `perform_request'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-net_http-2.1.0/lib/faraday/adapter/net_http.rb:66:in `block in call'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-2.3.0/lib/faraday/adapter.rb:45:in `connection'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-net_http-2.1.0/lib/faraday/adapter/net_http.rb:65:in `call'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-2.3.0/lib/faraday/middleware.rb:17:in `call'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-2.3.0/lib/faraday/middleware.rb:17:in `call'
        from /home/dependabot/dependabot-script/.bundle/gems/octokit-5.2.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
        from /home/dependabot/dependabot-script/.bundle/gems/octokit-5.2.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-2.3.0/lib/faraday/rack_builder.rb:153:in `build_response'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-2.3.0/lib/faraday/connection.rb:445:in `run_request'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-2.3.0/lib/faraday/connection.rb:200:in `get'
        from /home/dependabot/dependabot-script/.bundle/gems/sawyer-0.9.2/lib/sawyer/agent.rb:99:in `call'
        from /home/dependabot/dependabot-script/.bundle/gems/octokit-5.2.0/lib/octokit/connection.rb:156:in `request'
        from /home/dependabot/dependabot-script/.bundle/gems/octokit-5.2.0/lib/octokit/connection.rb:19:in `get'
        from /home/dependabot/dependabot-script/.bundle/gems/octokit-5.2.0/lib/octokit/client/contents.rb:40:in `contents'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/clients/github_with_retries.rb:101:in `public_send'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/clients/github_with_retries.rb:101:in `block in method_missing'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/clients/github_with_retries.rb:121:in `retry_connection_failures'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/clients/github_with_retries.rb:98:in `method_missing'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:239:in `fetch_github_file_list'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:220:in `fetch_dependency_file_list'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:215:in `dependency_file_list'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:113:in `changelog_from_ref'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:101:in `default_branch_changelog'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:64:in `changelog'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:33:in `changelog_url'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base.rb:40:in `changelog_url'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/pull_request_creator/message_builder.rb:341:in `changelog_url'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/pull_request_creator/message_builder.rb:306:in `metadata_links_for_dep'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/pull_request_creator/message_builder.rb:293:in `metadata_links'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/pull_request_creator/message_builder.rb:56:in `commit_message'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/pull_request_creator.rb:132:in `github_creator'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/pull_request_creator.rb:102:in `create'
        from ./generic-update-script.rb:150:in `block in <main>'
        from ./generic-update-script.rb:93:in `each'
        from ./generic-update-script.rb:93:in `<main>'
/usr/local/lib/ruby/2.7.0/net/http.rb:960:in `initialize': Failed to open TCP connection to api.github.com:443 (getaddrinfo: Temporary failure in name resolution) (SocketError)
        from /usr/local/lib/ruby/2.7.0/net/http.rb:960:in `open'
        from /usr/local/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
        from /usr/local/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
        from /usr/local/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
        from /usr/local/lib/ruby/2.7.0/net/http.rb:958:in `connect'
        from /usr/local/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
        from /usr/local/lib/ruby/2.7.0/net/http.rb:932:in `start'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-net_http-2.1.0/lib/faraday/adapter/net_http.rb:137:in `request_via_get_method'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-net_http-2.1.0/lib/faraday/adapter/net_http.rb:128:in `request_with_wrapped_block'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-net_http-2.1.0/lib/faraday/adapter/net_http.rb:121:in `perform_request'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-net_http-2.1.0/lib/faraday/adapter/net_http.rb:66:in `block in call'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-2.3.0/lib/faraday/adapter.rb:45:in `connection'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-net_http-2.1.0/lib/faraday/adapter/net_http.rb:65:in `call'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-2.3.0/lib/faraday/middleware.rb:17:in `call'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-2.3.0/lib/faraday/middleware.rb:17:in `call'
        from /home/dependabot/dependabot-script/.bundle/gems/octokit-5.2.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
        from /home/dependabot/dependabot-script/.bundle/gems/octokit-5.2.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-2.3.0/lib/faraday/rack_builder.rb:153:in `build_response'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-2.3.0/lib/faraday/connection.rb:445:in `run_request'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-2.3.0/lib/faraday/connection.rb:200:in `get'
        from /home/dependabot/dependabot-script/.bundle/gems/sawyer-0.9.2/lib/sawyer/agent.rb:99:in `call'
        from /home/dependabot/dependabot-script/.bundle/gems/octokit-5.2.0/lib/octokit/connection.rb:156:in `request'
        from /home/dependabot/dependabot-script/.bundle/gems/octokit-5.2.0/lib/octokit/connection.rb:19:in `get'
        from /home/dependabot/dependabot-script/.bundle/gems/octokit-5.2.0/lib/octokit/client/contents.rb:40:in `contents'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/clients/github_with_retries.rb:101:in `public_send'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/clients/github_with_retries.rb:101:in `block in method_missing'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/clients/github_with_retries.rb:121:in `retry_connection_failures'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/clients/github_with_retries.rb:98:in `method_missing'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:239:in `fetch_github_file_list'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:220:in `fetch_dependency_file_list'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:215:in `dependency_file_list'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:113:in `changelog_from_ref'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:101:in `default_branch_changelog'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:64:in `changelog'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:33:in `changelog_url'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base.rb:40:in `changelog_url'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/pull_request_creator/message_builder.rb:341:in `changelog_url'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/pull_request_creator/message_builder.rb:306:in `metadata_links_for_dep'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/pull_request_creator/message_builder.rb:293:in `metadata_links'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/pull_request_creator/message_builder.rb:56:in `commit_message'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/pull_request_creator.rb:132:in `github_creator'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/pull_request_creator.rb:102:in `create'
        from ./generic-update-script.rb:150:in `block in <main>'
        from ./generic-update-script.rb:93:in `each'
        from ./generic-update-script.rb:93:in `<main>'
/usr/local/lib/ruby/2.7.0/net/http.rb:960:in `initialize': getaddrinfo: Temporary failure in name resolution (SocketError)
        from /usr/local/lib/ruby/2.7.0/net/http.rb:960:in `open'
        from /usr/local/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
        from /usr/local/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
        from /usr/local/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
        from /usr/local/lib/ruby/2.7.0/net/http.rb:958:in `connect'
        from /usr/local/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
        from /usr/local/lib/ruby/2.7.0/net/http.rb:932:in `start'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-net_http-2.1.0/lib/faraday/adapter/net_http.rb:137:in `request_via_get_method'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-net_http-2.1.0/lib/faraday/adapter/net_http.rb:128:in `request_with_wrapped_block'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-net_http-2.1.0/lib/faraday/adapter/net_http.rb:121:in `perform_request'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-net_http-2.1.0/lib/faraday/adapter/net_http.rb:66:in `block in call'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-2.3.0/lib/faraday/adapter.rb:45:in `connection'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-net_http-2.1.0/lib/faraday/adapter/net_http.rb:65:in `call'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-2.3.0/lib/faraday/middleware.rb:17:in `call'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-2.3.0/lib/faraday/middleware.rb:17:in `call'
        from /home/dependabot/dependabot-script/.bundle/gems/octokit-5.2.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
        from /home/dependabot/dependabot-script/.bundle/gems/octokit-5.2.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-2.3.0/lib/faraday/rack_builder.rb:153:in `build_response'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-2.3.0/lib/faraday/connection.rb:445:in `run_request'
        from /home/dependabot/dependabot-script/.bundle/gems/faraday-2.3.0/lib/faraday/connection.rb:200:in `get'
        from /home/dependabot/dependabot-script/.bundle/gems/sawyer-0.9.2/lib/sawyer/agent.rb:99:in `call'
        from /home/dependabot/dependabot-script/.bundle/gems/octokit-5.2.0/lib/octokit/connection.rb:156:in `request'
        from /home/dependabot/dependabot-script/.bundle/gems/octokit-5.2.0/lib/octokit/connection.rb:19:in `get'
        from /home/dependabot/dependabot-script/.bundle/gems/octokit-5.2.0/lib/octokit/client/contents.rb:40:in `contents'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/clients/github_with_retries.rb:101:in `public_send'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/clients/github_with_retries.rb:101:in `block in method_missing'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/clients/github_with_retries.rb:121:in `retry_connection_failures'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/clients/github_with_retries.rb:98:in `method_missing'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:239:in `fetch_github_file_list'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:220:in `fetch_dependency_file_list'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:215:in `dependency_file_list'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:113:in `changelog_from_ref'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:101:in `default_branch_changelog'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:64:in `changelog'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:33:in `changelog_url'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base.rb:40:in `changelog_url'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/pull_request_creator/message_builder.rb:341:in `changelog_url'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/pull_request_creator/message_builder.rb:306:in `metadata_links_for_dep'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/pull_request_creator/message_builder.rb:293:in `metadata_links'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/pull_request_creator/message_builder.rb:56:in `commit_message'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/pull_request_creator.rb:132:in `github_creator'
        from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/pull_request_creator.rb:102:in `create'
        from ./generic-update-script.rb:150:in `block in <main>'
        from ./generic-update-script.rb:93:in `each'
        from ./generic-update-script.rb:93:in `<main>'
```

**Comment by jeffwidman** [comment]
👋 Sorry for the delay here, this repo is a "community service" for those wanting to run Dependabot on other platforms so responding to issues is a "best effort as we have time" kind of thing.

A couple of things:
1. Curious why you're leveraging `dependabot-script`? GHES natively includes [dependabot-as-an-action](https://github.com/github/dependabot-action). If you're trying to debug something that's broken in Dependabot, I suggest running [the dry-run script](https://github.com/dependabot/dependabot-core/#dry-run-script).
2. Given that you're a paid GHES customer, you can also receive faster support by filing a support ticket.

As an aside, for why it connects to api.github.com, my initial guess is that it's trying to fetch metadata for some dependencies. We have a long term goal of ensuring that Dependabot can run in a full air-gapped environment, but there's still a few calls that we need to cut off... many of which actually don't come from Dependabot itself but rather than native helpers that we shell out to. But we've been making incremental improvements there.

I'm going to close as I think this is more of a support question, and not a bug in `dependabot-script`, but if I'm wrong please comment and we can re-open.
