### ISSUE TITLE
git_metadata_fetcher /usr/lib/ruby/2.7.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): 

### ISSUE THREAD

**Issue by yeikel** [dependabot/dependabot-script#862]
I am seeing the following exception using a self hosted version of dependabot script and I am not quite sure what is the root cause of this

```
/usr/lib/ruby/2.7.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): "https://x-access-token:****@github.com/org/repo.git/info/refs?service=git-upload-pack" (URI::InvalidURIError)

[2021-08-12T16:55:29.612Z] 	from /usr/lib/ruby/2.7.0/uri/rfc3986_parser.rb:73:in `parse'

[2021-08-12T16:55:29.612Z] 	from /usr/lib/ruby/2.7.0/uri/common.rb:234:in `parse'

[2021-08-12T16:55:29.612Z] 	from /home/dependabot/dependabot-script/.bundle/gems/excon-0.85.0/lib/excon.rb:121:in `new'

[2021-08-12T16:55:29.612Z] 	from /home/dependabot/dependabot-script/.bundle/gems/excon-0.85.0/lib/excon.rb:250:in `get'

[2021-08-12T16:55:29.612Z] 	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.157.2/lib/dependabot/git_metadata_fetcher.rb:86:in `fetch_raw_upload_pack_for'

[2021-08-12T16:55:29.612Z] 	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.157.2/lib/dependabot/git_metadata_fetcher.rb:53:in `fetch_upload_pack_for'

[2021-08-12T16:55:29.612Z] 	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.157.2/lib/dependabot/git_metadata_fetcher.rb:17:in `upload_pack'

[2021-08-12T16:55:29.612Z] 	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.157.2/lib/dependabot/git_metadata_fetcher.rb:129:in `parse_refs_for_upload_pack'

[2021-08-12T16:55:29.612Z] 	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.157.2/lib/dependabot/git_metadata_fetcher.rb:123:in `refs_for_upload_pack'

[2021-08-12T16:55:29.612Z] 	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.157.2/lib/dependabot/git_metadata_fetcher.rb:29:in `ref_names'

[2021-08-12T16:55:29.612Z] 	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.157.2/lib/dependabot/pull_request_creator/github.rb:57:in `branch_exists?'

[2021-08-12T16:55:29.612Z] 	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.157.2/lib/dependabot/pull_request_creator/github.rb:41:in `create'

[2021-08-12T16:55:29.612Z] 	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.157.2/lib/dependabot/pull_request_creator.rb:102:in `create'
```

**Comment by jeffwidman** [comment]
👋 Sorry for the slow reply.

This is most probably a config / user error.

`dependabot-script` is offered as a resource to the broader community, but isn't something we can provide how-to support for. So I'm going to close this.

If you are able to debug further and identify an actual bug, then I'd be happy to take another look.
