### ISSUE TITLE
 Scan the terraform modules to check whether the version is outdated or not

### ISSUE THREAD

**Issue by sasi928** [dependabot/dependabot-script#945]
My goal is to scan the terraform modules to check whether the version is outdated or not. My terraform modules are located in Azure DevOps. We can Identify the dependencies. We are unable to access modules, which are both private and public. Mean while we are getting this issue I am looking for a solution. 

Parsing dependencies information
  - Updating hashicorp/azuread (from 2.36.0)… submitted
  - Updating hashicorp/azurerm (from 3.50.0)… submitted
/home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/git_metadata_fetcher.rb:58:in `fetch_upload_pack_for': 
The following git URLs could not be retrieved: https://*@dev.azure.com/ABCDEF/_git/resource-group1 (Dependabot::GitDependenciesNotReachable)
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/git_metadata_fetcher.rb:17:in `upload_pack'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/git_metadata_fetcher.rb:37:in `head_commit_for_ref'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/git_commit_checker.rb:83:in `head_commit_for_current_branch'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-terraform-0.209.0/lib/dependabot/terraform/update_checker.rb:126:in `latest_version_for_git_dependency'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-terraform-0.209.0/lib/dependabot/terraform/update_checker.rb:17:in `latest_version'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-terraform-0.209.0/lib/dependabot/terraform/update_checker.rb:37:in `updated_requirements'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/update_checkers/base.rb:285:in `changed_requirements'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/update_checkers/base.rb:275:in `requirements_up_to_date?'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/update_checkers/base.rb:35:in `up_to_date?'
	from ./generic-update-script.rb:187:in `block in <main>'
	from ./generic-update-script.rb:176:in `each'
	from ./generic-update-script.rb:176:in `<main>'

**Comment by jeffwidman** [comment]
We've updated this repo's README with a [deprecation note](https://github.com/dependabot/dependabot-script?tab=readme-ov-file#this-repo-is-deprecated) which points to a [new example repo](https://github.com/dependabot/example-cli-usage/) we setup to demonstrate how to self-host Dependabot using the [Dependabot CLI](https://github.com/dependabot/cli). As a result, we are archiving this repo.
