### ISSUE TITLE
pyenv: version `3.10.5' is not installed for poetry (pip)

### ISSUE THREAD

**Issue by sthiruko** [dependabot/dependabot-script#947]
This seems to be same as #477 with a newer python version and dependabot-python-0.209.0

Parsing dependencies information
/home/dependabot/dependabot-script/.bundle/gems/dependabot-python-0.209.0/lib/dependabot/python/update_checker/poetry_version_resolver.rb:325:in `run_poetry_command': pyenv: version `3.10.5' is not installed (set by /home/dependabot/dependabot-script/dependabot_tmp_dir/.python-version) (Dependabot::SharedHelpers::HelperSubprocessFailed)
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-python-0.209.0/lib/dependabot/python/update_checker/poetry_version_resolver.rb:91:in `block (2 levels) in fetch_latest_resolvable_version_string'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/shared_helpers.rb:168:in `with_git_configured'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-python-0.209.0/lib/dependabot/python/update_checker/poetry_version_resolver.rb:77:in `block in fetch_latest_resolvable_version_string'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/shared_helpers.rb:49:in `block in in_a_temporary_directory'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/shared_helpers.rb:49:in `chdir'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/shared_helpers.rb:49:in `in_a_temporary_directory'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-python-0.209.0/lib/dependabot/python/update_checker/poetry_version_resolver.rb:76:in `fetch_latest_resolvable_version_string'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-python-0.209.0/lib/dependabot/python/update_checker/poetry_version_resolver.rb:49:in `latest_resolvable_version'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-python-0.209.0/lib/dependabot/python/update_checker.rb:43:in `latest_resolvable_version'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/update_checkers/base.rb:74:in `preferred_resolvable_version'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/update_checkers/base.rb:257:in `preferred_version_resolvable_with_unlock?'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/update_checkers/base.rb:249:in `numeric_version_can_update?'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/update_checkers/base.rb:199:in `version_can_update?'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/update_checkers/base.rb:44:in `can_update?'
	from ./azure-update-script.rb:216:in `block in <main>'
	from ./azure-update-script.rb:196:in `each'
	from ./azure-update-script.rb:196:in `<main>'

**Comment by jeffwidman** [comment]
We've updated this repo's README with a [deprecation note](https://github.com/dependabot/dependabot-script?tab=readme-ov-file#this-repo-is-deprecated) which points to a [new example repo](https://github.com/dependabot/example-cli-usage/) we setup to demonstrate how to self-host Dependabot using the [Dependabot CLI](https://github.com/dependabot/cli). As a result, we are archiving this repo.
